### ISSUE TITLE
Tailoring wrong recipes/material price

### ISSUE THREAD

**Issue by dimitrisal** [ukon1990/wow-auction-helper#106]
I am checking on tailoring the recipe for Shrouded Cloth Cape. In the website it says it needs 1x Penumbra Thread with 4g minimum cost  while in reality is 4x Penumbra Thread at 9g each

**Comment by ukon1990** [comment]
Thanks for the report. This should be corrected as of earlier today.

If it does not appear correctly for you now, try to manually re-download the recipes and npc data(Download button -> and then in the popup)
