### ISSUE TITLE
Typo 'bargains'

### ISSUE THREAD

**Issue by Pulz-TCP** [ukon1990/wow-auction-helper#107]
Sorry for the grammar nazi-ism.

[/about/what-is](https://wah.jonaskf.net/about/what-is)
> This is a web application, developed with the intention of helping the user earn gold. Be it by crafting, snatching up **_bargans_**, checking out price trends, resetting a market, Or maybe just checking out the trade vendors.

**Comment by ukon1990** [comment]
Thanks for the report. It will be fixed as of the next release!

No worries, feel free to report more if you find them!
