### ISSUE TITLE
"Use without registration" looping

### ISSUE THREAD

**Issue by kkt-tc** [ukon1990/wow-auction-helper#108]
Sorry to bother, but it seems like the website is not accessible anymore for users that are not registered. 

Upon enterting the webstie, one can choose "Use without registration" and complete the setup; then the webstie reload with the prompt for "login"/"Use without registration" again locking the frontend interface, thus forming an self-loop.

I am not sure whether it's a bug or intentional. Might be good to just remove "Use without registration" if it is as expected. Thanks!

**Comment by ukon1990** [comment]
Ahh, thanks for the report. Il'l look into it!

Sorry for the slow reply…

**Comment by ukon1990** [comment]
Fixed this earlier today, sorry for being slow at seeing the GitHub issue…

**Comment by kkt-tc** [comment]
No no, not a problem at all. Thank you very much!
