### ISSUE TITLE
Sell price scaling from ilevel.

### ISSUE THREAD

**Issue by develflowing** [ukon1990/wow-auction-helper#116]
Hello. 
Any solution? wowhead I think have a scale of item level and sale to vendor price. I checked on one item - it's 11.03% price change beetween item levels. I didn't understand how to use ITEM CURVES from https://www.raidbots.com/developers
Any help?
Thanks.

__Originally posted by @develflowing in https://github.com/ukon1990/wow-auction-helper/issues/88#issuecomment-864262277__

**Comment by ukon1990** [comment]
Hmm, I can try to look into this again.
Currently, the retail items are being used for classic. This is something that I have to fix.

I would assume that for most items, this will fix the vendor price. But likely not for armor and weapons.

Thanks for the report.
