### ISSUE TITLE
No Auction Data when logged in

### ISSUE THREAD

**Issue by Rerox-WoW** [ukon1990/wow-auction-helper#123]
There seems to be a problem with registered users. When I am signed in no Auction Data can be loaded (Auction download failed undefined/undefined) and I can not select a Realm on the top of the page. I can select a faction, but the Realm dropdown doesn't work. When I log out and use the system as unregistered user it works fine.
![Screenshot 2021-07-15 111321](https://user-images.githubusercontent.com/67902928/125762787-e2b5d004-382c-4215-b366-431687c8a355.png)

**Comment by ukon1990** [comment]
Hmm, that is not good.
A bit of vacation mode here, so sorry for the delay. Il'l look into it now.

**Comment by Rerox-WoW** [comment]
Hey thanks, no problem, take your time and enjoy your vacation!

**Comment by ukon1990** [comment]
@Rerox-WoW 
I found a bug for classic realms, if this is what you were using. It should be working correctly now.

Your selected auction house was not saved correctly (Alliance, Horde or Neutral).

Did this solve it for you? (version 3.31.2)

**Comment by Rerox-WoW** [comment]
Yes it works! Great thanks!
