### ISSUE TITLE
Crafting > Consumables > Food & Drinks shows content of "Bandages", while "Bandages" shows no items

### ISSUE THREAD

**Issue by jck0p** [ukon1990/wow-auction-helper#131]
Looks like the categories got mixed up:

https://i.imgur.com/mUTKoBW.png

https://i.imgur.com/NEZfXxM.png

**Comment by ukon1990** [comment]
Thanks for the report, Il'l try to look at it tomorrow (CET)

**Comment by ukon1990** [comment]
Live as of version 3.33.2.
Again, thanks for the report. Sorry about being so slow on fixing the issue.
