### ISSUE TITLE
Sunmote and heart of darkness could not be found

### ISSUE THREAD

**Issue by adeemon** [ukon1990/wow-auction-helper#142]
As i user i want to open the sunmote and heart of darkness page with history, realm compare etc
When i write it in the search field, the results are empty
https://sun9-north.userapi.com/sun9-81/s/v1/ig2/ChyINpnEaOCbuoQDjqj-IkEdnO0HCBq5x6McF63E-N6VqJZ4krbVWJTInfu0bvvf63pIC0D4PMwmKjA_6Y_97abd.jpg?size=1862x226&quality=96&type=album

But i can see the current price of sunmote on the "Crafting" page.
https://sun9-east.userapi.com/sun9-18/s/v1/ig2/1fKvYzFPbFX2iXvp1SQMgjL9C1LZnCoTiv4X-rAhQ7nKbj6v08nO3IT29beLFQ_G21TwDuIKDZCypz3QmTL3ixGl.jpg?size=845x836&quality=96&type=album

**Comment by ukon1990** [comment]
Thanks for the report. I’ll look into it as soon as I can get some free time.

**Comment by ukon1990** [comment]
Sunmote and heart of darkness etc are now available in the app!
If it for some reason isn't appearing t you automatically, then open the download panel (where the AH update timer is) and manually trigger the download.
