### ISSUE TITLE
Prices are off

### ISSUE THREAD

**Issue by FlamingFlamingo42** [ukon1990/wow-auction-helper#144]
Hi,

I really appreciate your tool.
For some reason the prices are a bit off on the website.

For example:
Perenolde - EU - Horde

Deadly Sinvyr Ring ilvl 151
- WAH: Buyout price: 89,000g
- TSM:  Buyout price:  ~1,300g

It could be a fault on my side, but it's really confusing.

Thanks in advance.

**Comment by ukon1990** [comment]
Thank you for the report, I can try to look more into it when I get home.

I can see that there are two supposedly identical items at different price for some reason(checked on your realm).
<img width="2015" alt="Skjermbilde 2022-07-18 kl  09 17 56" src="https://user-images.githubusercontent.com/10864030/179471830-7443e9c1-1ad4-4746-9090-6ec0cdf8a50e.png">

**Comment by ukon1990** [comment]
I have had less time available lately than I expected, so I am a bit unsure of when I can get time to fix the issue. But I am aware of it, and will fix it as soon as I have time.

**Comment by ukon1990** [comment]
Fix is live now as of version 3.33.5. You should no longer experience this, if the issue is what I thought it was.
