### ISSUE TITLE
how can i copy/paste the results so i can import to my TSM?

### ISSUE THREAD

**Issue by jBbL81** [ukon1990/wow-auction-helper#160]
for example, if i go to wowhead and get a list of all the items that are ilvl 350, i can highlight all of them to copy and then paste to https://www.tradeskillmaster.com/group-maker/create and i will be given a list of import strings that i can use on my tsm

how can i do this on https://wah.jonaskf.net/auctions ? i tried copy/pasting but obviously it doesn't work otherwise i wouldn't be here asking.

**Comment by ukon1990** [comment]
Hi, sorry for the late reply. Thanks for the feedback!

I've added the item id's in the item details page now, so you can copy it from there.
