### ISSUE TITLE
Bfa reputation recipe progress

### ISSUE THREAD

**Issue by ukon1990** [ukon1990/wow-auction-helper#34]
The ability to see what reputations you need on your crafters
- [x] Gather quartermaster data
- [x] Correspond vendor id with reputation
- [x] Create the visualisation

**Comment by insanepoet** [comment]
https://gist.github.com/insanepoet/febfd3798f43bd3d175502d69e51089f

This may help, all reputation vendor recipes from BfA as well as their respective reputations required.

**Comment by ukon1990** [comment]
Nice, I am certain that this would help!

**Comment by ukon1990** [comment]
This is now implemented and pushed to prod as of version 2.177.0.
[https://wah.jonaskf.net/tools/reputations](https://wah.jonaskf.net/tools/reputations)
