### ISSUE TITLE
My auctions characters not appearing

### ISSUE THREAD

**Issue by ukon1990** [ukon1990/wow-auction-helper#41]
This only seem to occur on some realms.
Aman'thul being one of them.

The API returns Aman'Thul for auctions and Aman'thul for characters.

This is causing it not to work as expected.
- [x] Turn all realm ID's to lowercase
- [x] Fix the character encoding issue for the auction lambda

**Comment by fabriciomind** [comment]
Not appearing here too.
Realm: Goldrinn
Char: Badunça

**Comment by ukon1990** [comment]
@fabriciomind Turns out that it actually is an error on my end. Thank you for bringing this to my attention.

**Comment by fabriciomind** [comment]
Nice @ukon1990 !

I'll check it as soon as I get home!

Thank you!

**Comment by ukon1990** [comment]
@fabriciomind It seems like it is taking me longer than expected to fix this, due to things I have to do in real life too. But I am still working on it and it will be live as soon as it is fixed.

**Comment by ukon1990** [comment]
So an update regarding this issue @fabriciomind .
I have still not found the time to complete this fix yet.

The issue happens because the compression I use in the current Lambda (only used for US users) has issues with special characters. I could not found a reasonable solution to that issue, without hosting an additional server in the US with Elastic Load Balancer and all that. But I would prefer to keep the hosting costs low, if possible. And that would probably double the hosting cost.

So the way I plan on solving this, is by using AWS's S3 to store gzipped auction data via a Lambda function. I don't think that I will have the time to get into this issue until mid december(parental leave).

I'm sorry for the inconvinience that this issue causes/caused for you and others whom may experience this issue.

**Comment by ochevidnost** [comment]
Doesn't work for me either (and never worked)
Realm: EU Razuvious
Char: Продаван

Russian servers and/or character names not supported using UTF-8 ?

**Comment by ukon1990** [comment]
> Doesn't work for me either (and never worked)
> Realm: EU Razuvious
> Char: Продаван
> 
> Russian realms and/or character names not supported using UTF-8 ?
> There are no special characters, Blizz doesn't allow them here, only plain russian alphabet.

Greetings, sorry about the slow reply. It seems like I can search your character up when I go to https://wah.jonaskf.net/tools/sellers, so it is getting there correctly from blizzard I think.

But when I add you to my characters. It does not appear in the auctions section. Il'l try to look further into it tonight, and thank you for reporting.

**Comment by ukon1990** [comment]
> Doesn't work for me either (and never worked)
> Realm: EU Razuvious
> Char: Продаван
> 
> Russian realms and/or character names not supported using UTF-8 ?
> There are no special characters, Blizz doesn't allow them here, only plain russian alphabet.

Greetings, sorry about the slow reply. It seems like I can search your character up when I go to https://wah.jonaskf.net/tools/sellers, so it is getting there correctly from blizzard I think.

But when I add you to my characters. It does not appear in the auctions section. Il'l try to look further into it tonight, and thank you for reporting.

**Comment by ukon1990** [comment]
@ochevidnost An update. It seems like it helps if the app uses ru_RU locales for fetching the realm list. But then TSM won't know what realm I am looking for, as the slug(url friendly name) of the realm won't match what TSM have.

Will look further into it, when I have time again. Sorry for the inconvinience. This should not require a change in the back-end, unlike the US special character issue.

**Comment by ukon1990** [comment]
@ochevidnost Hi, the problem seems to be fixed as of v2.174.4.

**Comment by ukon1990** [comment]
> Not appearing here too.
> Realm: Goldrinn
> Char: Badunça
> 
> I can find the auctions under this name: BadunÃ§a. This should be the problem, since the char was imported with the correct name.

Greetings, this issue has finally been resolved.
I'm sorry that it took this long...

One of the causes for this issue, was caused by a misconfigured AWS API Gateway. As the US auctions were fetched via a AWS Lambda function. But as this issue has been resolved, all regions now use the AWS Lambda function.
