### ISSUE TITLE
How to hide default Groups e.g. "Profitable crafts"

### ISSUE THREAD

**Issue by pcmdWoW** [ukon1990/wow-auction-helper#43]
Hi,

firstly thank you for the amazing tool! There is only one thing I dont like . How can I remove the default groups shown in the dashboard? For Instance "Profitable crafts" or "Profitable ore to prospect" 

I would like to use the dashboard as a daily check for my custom groups without having all the default groups shown.

**Comment by Maldark** [comment]
Hi,

You should be able to modify the default dashboard here: https://wah.jonaskf.net/dashboard/manage-dashboards

**Comment by ukon1990** [comment]
Hi @pcmdWoW!

Sorry for the slow reply, I do agree that it should be possible to hide it. And also modify the parameters that trigger them. Like @Maldark said, in the manage dashboards tab.

I have had an issue(https://github.com/ukon1990/wow-auction-helper/issues/25) up for this for a while, but I have not prioritised it over other things that I felt needed doing.

But I can move it up my priority list.
