### ISSUE TITLE
Undercut indication

### ISSUE THREAD

**Issue by ukon1990** [ukon1990/wow-auction-helper#48]
If the user has the lowest buyout, the auction is supposed to be highlighted in green text.

If there is someone else whom has posted for the same price, it should be orange or something.
- [ ] Only lowest buyout shall correctly appear as green text
- [ ] Lowest but not the only person auctions should be orange.
- [ ] Whitelist characters/players

**Comment by Maldark** [comment]
It would be useful if you could have list of whitelisted players in addition to your own characters of course. I.e. if I have multiple accounts where some items overlap, I don't want to compete in price against myself.

**Comment by ukon1990** [comment]
Yes, a whitelist option can be added!
