### ISSUE TITLE
Add support for a user to add missing items or recipes by item and spellID

### ISSUE THREAD

**Issue by ukon1990** [ukon1990/wow-auction-helper#5]
If a user can't find an item in the custom price search etc. They should be able to add it by itemID so that the item can be added to the wah-db. Same goes for missing recipes.
- [ ] A user should be able to update incorrect recipe data
- [ ] A user should be able to add new recipes & review their correctness before adding
- [ ] A user should be able to initiate an update for a recipes data
- [ ] Make it so that it does not collide with auto-updated recipes

**Comment by MarcusNewman** [comment]
Possibly related, can we have update ability for recipies with bad values? https://www.wowdb.com/spells/159674-mark-of-blackrock should be 3 temporal crystals and 5 Sorcerous Earth, instead is listed as .05 crystals and 0.083 x Sorcerous Earth
