### ISSUE TITLE
Server missing?!

### ISSUE THREAD

**Issue by mithandir** [ukon1990/wow-auction-helper#60]
Hi,
for some reason the server "Taerar" is missing for EU. It did exist in the past.

Thank you

![image](https://user-images.githubusercontent.com/446588/46945388-ed405480-d074-11e8-8642-f12d362c18be.png)

**Comment by ukon1990** [comment]
Thank you for reporting this. I could replicate it, and if I changed to the US, and then back to EU. The realm appeared again.

**Comment by ukon1990** [comment]
This issue should now be solved as of version 2.174.2.
If you are still getting the issue after this update, it might be due to the response being cached. This occured for me when the change went live, but a reload after the new version was installed solved that.
