### ISSUE TITLE
Add realm pls

### ISSUE THREAD

**Issue by Flow100** [ukon1990/wow-auction-helper#62]
hi can you add the realm    Blackroch - EU
thanks or i have no found in the list of EU-Server

**Comment by ukon1990** [comment]
Hi, the realm blackrock is supposed to be in the realm list.
The list is served by Blizzard. But it does seem like we are still getting some realms missing every now and then. Blackrock appeared for me when I visited a fresh "installation" of the app today.

But Il'l see if I can make a change that would hopefully avoid this kind of issue. And also allowing for manual input.

If you are still experiencing issues with this, try importing these settings instead in the "Import previous settings". You can add the other stuff in the settings later if you wish:
`
{
  "character": "undefined",
  "characters": [],
  "apiToUse": "none",
  "buyoutLimit": 200,
  "useIntermediateCrafting": true,
  "notifications": {
    "isUpdateAvailable": true,
    "isBelowVendorSell": true,
    "isUndercut": true,
    "isWatchlist": true
  },
  "isDarkMode": true,
  "realm": "blackrock",
  "apiTsm": "",
  "apiWoWu": "",
  "region": "eu"
}
`

**Comment by ukon1990** [comment]
And thank you for reporting the issue btw. I've madde a new git issue, that will make cases like this less bothersome for the user.

So for further conversation regarding this issue, please go to #63 instead.
