### ISSUE TITLE
Import TSM addon history not working

### ISSUE THREAD

**Issue by sugaraspa** [ukon1990/wow-auction-helper#67]
Nothing happens when clicking "Import TradeSkillMaster.lua" at https://wah.jonaskf.net/dashboard/tsm

(Chrome browser, deleted all variables and tried again)

**Comment by ukon1990** [comment]
It is weird that the file picker does not appear for you. I've re-tested this in Windows 10, Linux and macOS Mojave just now. And I don't seem to have any issues.

Do you have multiple chrome windows open? if so, does it appear in any of those instead?

Do you get any kind of errors in the developer console?

**Comment by sugaraspa** [comment]
Apologies, the file picker does appear for me, I select TradeSkillMaster.lua (correct file, correct directory), and then hit OK. 

At this point there's no visible state change in the page (i.e. it's still asking me to "Import TradeSkillMaster.lua", which I've done), and browsing the rest of the site there are no updated prices for anything.

So for example, [this is the screenshot](https://gm1.ggpht.com/VZSq070LfTelXWB0FtTrcV4Sh7NqR53D99sLomSdVax_nnBpBZ83SZXjBfcoO9O2UC-ILojKslcAhvRNfq1eFfqRU91NWtgoJ4EyHwAfF8a1AVyUzU4FaNRAO2BljrRIEXlr0dYf7p7EJ9mCr2A5xfaUa_dxQ7JAzzuTlhlsvg2vH6obzyiLwU6teVfh4n8jHyCmfgUu1kNapPMIy_rFqxUX5uY26RlBhAqqydZJ4pNNNEGckbgnNUohf_7oulDNfM3r9UNhlb8Q6VNq1MqL-IBclDA4kF9lVUn2DiXEVI0eAmOPu2Zgu5yLEoHY2SVZOWdmg_L5M3kiF1lWXKBCu4LO8S04i7QxlLJ5NAXBS4iaAPlTTfuAysiRpSDuX-R3heaHmarmyc_wadpDAYDAWgQh1nA_87hWulH_tr-ZR2SPXlUib9XiNiDx0W2Q6LYN4dG5Hvb9XVeifaumxgHdpc3X0UjxDdqXbgs-F8E2Y1t4wOAqlV6f8VYDg4Cy-Skcwr6QY0tcoroLr5HbH_ejZF6yoA8gAcusZmiCMI1H8k8zgeEjAcf-VG1lDacJ7wvtYL2DVtESfMINgrQey-EBs1dhaKl83ejBQPKqsqeA1UrV1qDcEmSdSDoF_aij8cuRvVxDrOWscZ8fgI1MIoTmG3KS9dEHukJP_OA_a4Bq0gBvGznV8KVMw5JHpaufGWLSvO6v0tH7cIXU2cqDeVgDQRxTdQ1OPkYlfeEX-ek=s0-l75-ft-l75-ft) both before and after I hit the import button.

Perhaps worth mentioning, as I don't know if it's related, the Auctions data is not being downloaded ([screenshot here](https://gm1.ggpht.com/L-o0e_zY4zo2Fla4wbg3S6t1dqGNAujNaBCRrzcn_CnYoAeNfNxm0k5nsSIx9gCQoELnBo6qdvcCx1kvkWT6oS2iyKktBA_flk3rLp01kXS2BMF_td3oYcPjfXUBE1F--4QTRpMXCFd3gdBMwJBqg7LCP0MtFyZ3nNrMJwaU6xkHHTw57z1J-K_pH5fTuz02tP7PPSOGdezoZQ4-gSdS_fNeSHrD2eP6uO-uTfiWQwZvZEiQjMGDgzY6_9_5xMtHogYks2wgMY1pUt-GH1rwp8coKMPtTcAx7pibcYIIiST49QTqgBhxe06Cnwn7VEN20IeU-JOYKW-fDlO9rmgl61pYJooWDB3A7i3EQDMcu6JWeeyhxYTUN-uHlaBmIgeW6LGG8lBn72XWzC0OB4Hjl6o3grmaXvmEWabfe6HPeeSMHfKihf2SW72p6xtDfm9oc9i0-h3pdebgZ0clKJTYS66QEdJ2sbaOJK-OYw8mqOFbCk53Ozr7aBxQzlmSyGxIsnX3rzypje-aEHHfOriSKiEcfRoa3OGbAJxlfBvPP0SQEDSBXPCSiKWleagJjiF0ocQmg8sq03FlY_7ZgZa508bA_N4Q3fBwfCPMOGShPb6ZFD21TvFml3MuFAAkAL1kAbLwIU8WtbtBulbgV5GfjmAcE_0-wSsXQRM1w_QMkpk3wXxzwHlhA1f1X847Pg2nkkvvy-hthoTeN5ZgU219JaCN8DhoM-dv9MeC=s0-l75-ft-l75-ft)).

**Comment by sugaraspa** [comment]
Apologies, the file picker does appear for me, I select TradeSkillMaster.lua (correct file, correct directory), and then hit OK.

At this point there's no visible state change in the page (i.e. it's still asking me to "Import TradeSkillMaster.lua", which I've done), and browsing the rest of the site there are no updated prices for anything.

So for example, [this is the screenshot](https://imgur.com/a/AkMvNED) both before and after I hit the import button.

Perhaps worth mentioning, as I don't know if it's related, the Auctions data is not being downloaded ([screenshot here](https://imgur.com/a/kD5WjjP)).

**Comment by ukon1990** [comment]
No problem!

I do assume that you are using TSM4, else then that might be the cause. I have not tested this functionality with TSM3.

Would you be able to take a screenshot of the developer console? (F12) Or even better, right click in the console and do save as, and link me the file.

___________
Regarding the auction data not being downloaded. That seems to be because my server in the US, is too far away from where Blizzard is hosting the auction data. I tested a couple of locations just now and I think that I found a better location(North California) to host it. Could you see if it downloads correctly for you from version 2.186.0?

I added a new GitHub issue for adding one that is located in Australia and on the east coast of the US.

Thank you for the report btw.
